### ISSUE TITLE
Model 3 and 4 DMK-images do not work

### ISSUE THREAD

**Issue by litwr2** [lkesteloot/trs80#1]
trs80-tool just crashes on the model 3 boot disk image.
It prints "Can only handle TRSDOS floppies" for the model 4 boot disk image.

**Comment by lkesteloot** [comment]
Can you send me a copy of those floppies? I think you can attach them here if you want.

**Comment by litwr2** [comment]
Thank you.  I work under Linux.  I just downloaded the binary file and tried to use it.  I use disk images that are built in trs80gp emu, I just exported them. Sorry, I confuse some things, It was the model 1 boot disk images that causes the crash.

**Comment by lkesteloot** [comment]
Okay, well please send me any image that crashes my software and I'll take a look! You can attach the DMK file to this bug.

**Comment by litwr2** [comment]
[m1-trsdos-blank.zip](https://github.com/lkesteloot/trs80/files/7019977/m1-trsdos-blank.zip)
other model I images also crash trs80-tool

**Comment by lkesteloot** [comment]
Okay I've fixed it so the floppy you attached no longer crashes. That'll be in the next release.
