### ISSUE TITLE
feature request: simpler batch conversion?

### ISSUE THREAD

**Issue by turnkit** [lkesteloot/trs80#6]
instead of getting "Must specify at least one infile and exactly one outfile" 

trs80-tool convert TRS104B.wav >> convertlog.txt

I have a folder full of .wav files -- could you make a way to automatically batch directory by:
> trs80-tool dir *.wav

and also convert in batch like
> trs80-tool convert *.wav

?

**Comment by lkesteloot** [comment]
You can already run the "dir" command with a wildcard (at least on Mac and Linux, not sure about Windows).

For the convert, do you want to extract the contents of all of the WAV files? Would you put each into its own new folder or something?

**Comment by lkesteloot** [comment]
Closing this issue because OP didn't respond to questions.
