### ISSUE TITLE
Discussions section

### ISSUE THREAD

**Issue by turnkit** [lkesteloot/trs80#7]
Lawrence, would you consider adding a discussion section?  I have feature requests but don't think they really should go in here as "issues", right?

Do you have Discord or other forum for discussion of your tools?

Q's:
1) when invoking TRS-TOOL it seems to take 6 to 8 seconds before responding. Is this normal?
2) would you consider adding some regex wildcard features for easy batch processing of multiple assets?  (See example below.)
3) don't CMD files and BAS files have the filename embedded into the WAV and CAS stream?  Can we get those names in the DIR cmd instead of only T1.3BN etc,?
4) are you looking for any .wav files for testing?  (See examples below.)
5) any idea why I might get a series of short -- 19 to 56 byte .bin files?  Are these likely BASIC cassette data writes?
6) any idea why I might have "truncated at start of block" files?

examples:
S:\out>..\trs80-tool.exe dir ..\TRS104B.wav
T1-C1.3BN        7  500 baud File is truncated at start of block
T1-C2.3BN        7  500 baud File is truncated at start of block

S:\out>..\trs80-tool.exe dir ..\TRS106A.wav
T1-C1.L1       973  250 baud
T1-C2.L1      1623  250 baud
T2-C1.BIN     2865  250 baud
T3-C1.L1       263  250 baud
T4-C1.BIN     1990  250 baud
T5-C1.L1      3669  250 baud

S:\out>..\trs80-tool.exe dir ..\TRS109B.wav
T1-C1.BIN        56  500 baud
T1-C2.BIN        35  500 baud
T1-C3.BIN        47  500 baud
T1-C4.BIN        30  500 baud
T1-C5.BIN        28  500 baud
T2-C1.BIN        20  500 baud
T3-C1.BIN        28  500 baud
T3-C2.BIN        19  500 baud
T3-C3.BIN        32  500 baud
T3-C4.BIN        19  500 baud
T4-C1.BIN        31  500 baud
T4-C2.BIN        50  500 baud
T5-C1.BIN        23  500 baud
T6-C1.BIN        38  500 baud
T7-C1.BIN        50  500 baud
T8-C1.BIN        39  500 baud
T9-C1.BIN        50  500 baud
T10-C1.BIN       31  500 baud
T11-C1.BIN       28  500 baud
T11-C2.BIN       30  500 baud
T12-C1.BIN       10  500 baud
T13-C1.BIN       10  500 baud
T14-C1.BIN       10  500 baud
T14-C2.BIN       10  500 baud
T15-C1.BIN       10  500 baud
T16-C1.BIN       10  500 baud
T17-C1.BIN       10  500 baud
T18-C1.BIN       10  500 baud
T18-C2.BIN       10  500 baud
T19-C1.BIN       10  500 baud

S:\out>..\trs80-tool.exe dir ..\TRS*.wav
Can't open "..\TRS*.wav": ENOENT: no such file or directory, open '..\TRS*.wav'

**Comment by lkesteloot** [comment]
I didn't even know Github had discussions! I've enabled it, if you want to repost your issue there. (You can also break it up into smaller posts to make the conversation easier to follow.)

**Comment by lkesteloot** [comment]
> when invoking TRS-TOOL it seems to take 6 to 8 seconds before responding. Is this normal?

No, it takes about 100ms on my machine (MacBook Pro).

> would you consider adding some regex wildcard features for easy batch processing of multiple assets?

That's because Windows doesn't expand wildcards. I suppose I could manually expand those on Windows. Can you open a new issue for that?

> don't CMD files and BAS files have the filename embedded into the WAV and CAS stream? Can we get those names in the DIR cmd instead of only T1.3BN etc,?

WAV and CAS files don't include CMD files. They do include BAS files, but those don't have filenames. (They have a one-letter name, but that's typically junk.)

> are you looking for any .wav files for testing?

Sure!

> any idea why I might get a series of short -- 19 to 56 byte .bin files? Are these likely BASIC cassette data writes?
> any idea why I might have "truncated at start of block" files?

I'd have to look at the WAV file.

**Comment by lkesteloot** [comment]
No response, I'm closing this issue.
